// <auto-generated />
using System;
using AcoesDotNet.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcoesDotNet.Dal.Migrations
{
    [DbContext(typeof(AcoesDataContext))]
    partial class AcoesDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcoesDotNet.Model.Acao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoDaAcao")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("DataCotacao");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Acoes");
                });

            modelBuilder.Entity("AcoesDotNet.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CnpjCpf")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AcoesDotNet.Model.Ordem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<string>("CodigoAcao")
                        .IsRequired();

                    b.Property<DateTime?>("DataCompra");

                    b.Property<DateTime>("DataOrdem");

                    b.Property<int>("IdCliente");

                    b.Property<decimal>("ImpostoRenda");

                    b.Property<int>("QuantidadeAcoes");

                    b.Property<decimal>("TaxaCorretagem");

                    b.Property<string>("TipoOrdem")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<decimal>("ValorOrdem");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ordens");
                });

            modelBuilder.Entity("AcoesDotNet.Model.Ordem", b =>
                {
                    b.HasOne("AcoesDotNet.Model.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });
#pragma warning restore 612, 618
        }
    }
}
